name: tests
on: [push, pull_request]
jobs:
  tests:
    strategy:
      matrix:
        go: [1.12.x, 1.13.x, 1.14.x, 1.15.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v1
      - run: go test -cover ./...
